#!/bin/bash

# distrib=$(lsb_release -i | cut -d : -f 2)
# export TEXTDOMAINDIR="/usr/share/locale/"
export TEXTDOMAIN="verifMario"
distrib=""

serverUrl="https://www-info.iutv.univ-paris13.fr/verifMario.d/"
serverPOST="$serverUrl/.eval.php" # url ou envoyer la requete
# serverPOST="http://192.168.1.24/server/.eval.php"

packages="curl ssh jq yad"
projectFile="exerciceTP.mar"
requestName=".requetes.json"
idSsh=".id_rsa_marionnet"
file="$idSsh"
prefixDir="exo"
timing=1200 # temps en seconde
PARSER='OFS="\n" {print $1, $2, $3, $4, $5; fflush()}'
TMPVERIF=$(mktemp -d)
TMPFILE="$TMPVERIF/tmpfile"
TMPBUFF="$TMPVERIF/tmpbuff"
touch $TMPFILE
touch $TMPBUFF
# mkfifo $TMPBUFF
response=""
projectListName="$serverUrl/.projectList"
projectList=""

name=""
firstName=""
projectName=""
choice=""
back=0

declare -A dataRequest
declare data
declare -A cable
declare -A dataResponse

nbCable=0
nbLine=0

function helpFunc() {
    echo $"Usage : $0 [option]

Option :
--help ................ show help
--debug ............... debug mode
--text ................ text mode"
    exitFunc 0
}

debug=0
graph=1
exam=$([ $0 == './examMario' ] && echo 1 || echo 0)
TMPDIR=$([ "A$TMPDIR" = "A" ] && echo /tmp || echo $TMPDIR)

export tty=$(tty)

# echo_debug <msg> [sortie]
function echo_debug() {
    if [ "A$1" != "A" ]; then
        local out=$([ "$2" = "err" ] && echo /dev/stderr || echo $tty) # sortir par défaut : stdout
        [ $debug -eq 1 ] && echo -e $1 > $out
    fi
}

# echo_err <msg>
function echo_err() {
    if [ "A$1" != "A" ]; then
        if [ $graph -eq 0 ]; then
            echo -e "\e[31mERROR :\e[0m $1" > /dev/stderr
        else
            yad --image emblem-important \
            --title ERROR --text "ERROR : $1" \
            --button gtk-ok \
            --on-top --mouse
        fi
    fi
}

# exitFunc <val>
function exitFunc() {
    if [ "A$1" != "A" ]; then
        rm -rf $TMPVERIF
        exit $1
    fi
}

if [ $# -ge 1 ]; then
    for i in $(seq 1 $#); do
        if [ "$1" == "--debug" ]; then debug=1
        elif [ "$1" == "--text" ]; then graph=0
        elif [ "$1" == "--help" ]; then helpFunc
        else
            echo_err $"Unknown parameter"
            exitFunc 1
        fi
        shift
    done
fi

# marioSsh <machine> <cmd>
function marioSsh() {
    local cde=$0
    local PRIVATE_RSA_KEY=$projectName/$idSsh

    # we need more checks
    #-- Checks
    if [ "A$2" = "A" ]; then
        echo $"Usage: $cde  host cmd" > /dev/stderr
        echo_err $"Where host is the name of a virtual machine in marionnet"
        exitFunc 1
    fi

    local Host="$1"
    shift
    Cmd="$*"

    resu=`ps aw |grep marionnet|grep "hostname=$Host "|head -1|sed -e 's/^.* eth42=\([^ ]*\) .*$/\1/'`'/'
    if [ "$resu" = "/" ] ; then
        echo_err $"Machine or Router $Host not found or not running in current marionnet project"
        exitFunc 1
    fi

    local tap=`echo $resu | cut -d ',' -f 2`

    if [ "A$tap" = "A" ]; then
        echo_err $"Tap not found"
        exitFunc 1
    fi

    local ip=`/sbin/route -n |grep $tap |cut -d ' ' -f 1`
    
    if [ ! -f ~/.ssh/known_hosts ]; then
        touch ~/.ssh/known_hosts
    fi

    local pubKey=$(ssh-keyscan -t ecdsa $ip 2> /dev/null)
    local ref=$(grep $ip ~/.ssh/known_hosts | cut -d ' ' -f 3)
    local search=$(echo $pubKey | cut -d ' ' -f 3)

    if [ "$search" != "$ref" ]; then
        echo $pubKey >> ~/.ssh/known_hosts
    fi
    
    LC_ALL=C ssh -xq -i $PRIVATE_RSA_KEY root@$ip $Cmd
    if [ $? -eq 255 ]; then
        echo_debug $"\e[31mERROR :\e[0m Ssh connection failed with $Host" err
    fi
}

# cidr2mask <cidr>
function cidr2mask() {
    if [ "A$1" != "A" ]; then
        local decal=$(( 4 - ($1 / 8) ))
        local cutByte=$(( (255 << (8 - ($1 % 8))) & 255 ))
        set -- 255 255 255 255 $cutByte 0 0 0
        [ $decal -gt 0 ] && shift $decal
        echo ${1}.${2}.${3}.${4}
    fi
}

# testPresence <machine>
function testPresence() {
    if [ "A$1" != "A" ]; then
        ps aw | grep marionnet | grep -q "$1" && echo ok || echo ERROR 
    fi
}

# getIPAddress <machine> [interface]
function getIPAddress() {
    if [ "A$1" != "A" ]; then
        local eth=$([ "A$2" != "A" ] && echo $2 || echo eth0)
        local res=$(marioSsh $1 ip addr show $eth | grep 'net ' | awk '{print $2}' | cut -d '/' -f 1)
        [ "A$res" != "A" ] && echo $res || echo ERROR 
    fi
}

# getMask <machine> [interface]
function getMask() {
    if [ "A$1" != "A" ]; then
        local eth=$([ "A$2" != "A" ] && echo $2 || echo eth0)
        local cidr=$(marioSsh $1 ip addr show $eth | grep 'net ' | awk '{print $2}' | cut -d '/' -f 2)
        local res=$(cidr2mask $cidr)
        [ "A$res" != "A" ] && echo $res || echo ERROR 
    fi
}

# getCidrMask <machine> [interface]
function getCidrMask() {
    if [ "A$1" != "A" ]; then
        local eth=$([ "A$2" != "A" ] && echo $2 || echo eth0)
        local cidr=$(marioSsh $1 ip addr show $eth | grep 'net ' | awk '{print $2}' | cut -d '/' -f 2)
        [ "A$res" != "A" ] && echo $cidr || echo ERROR 
    fi
}

# getFullIP <machine> [interface]
function getFullIP() {
    if [ "A$1" != "A" ]; then
        local eth=$([ "A$2" != "A" ] && echo $2 || echo eth0)
        local res=$(marioSsh $1 ip addr show $eth | grep 'net ' | awk '{print $2}')
        [ "A$res" != "A" ] && echo $res || echo ERROR 
    fi
}

# getRoute <machine> <route>
function getRoute() {
    if [ "A$1" != "A" ] && [ "A$2" != "A" ]; then
        local route=$([ "$2" = "default" ] && echo '0.0.0.0' || echo $2)
        local res=$(marioSsh $1 route -n | grep "^$route")
        [ "A$res" != "A" ] && echo $res || echo ERROR 
    fi
}

# getNet <machine> [interface]
function getNet() {
    if [ "A$1" != "A" ]; then
        local eth=$([ "A$2" != "A" ] && echo $2 || echo eth0)
        local res=$(marioSsh $1 route -n | grep "U[^G] .* $eth$" | awk '{print $1}')
        [ "A$res" != "A" ] && echo $res || echo ERROR 
    fi
}

# pingMachine <machine1> <machine2> [interface]
function pingMachine() {
    if [ "A$1" != "A" ] && [ "A$2" != "A" ]; then
        local eth=$([ "A$3" != "A" ] && echo $3 || echo eth0)
        local ip=$(getIPAddress $2 $eth)
        if [ "$ip" = "ERROR" ]; then echo ERROR ; return; fi
        marioSsh $1 ping -c 1 -w 1 $ip &> /dev/null && echo ok || echo ERROR
    fi
}

# getCable <machine1> <machine2>
function getCable() {
    if [ "A$1" != "A" ] && [ "A$2" != "A" ]; then
        local res=$(echo ${cable[$1,$2]})
        [ "A$res" != "A" ] && echo $res || echo ERROR 
    fi
}

# checkIP <machine> <net> [interface]
function checkIP() {
    if [ "A$1" != "A" ] && [ "A$2" != "A" ]; then
        local eth=$([ "A$3" != "A" ] && echo $3 || echo eth0)
        local mask=$(getMask $1 $eth)
        local ip=$(getIPAddress $1 $eth)
        local net=$2
        local res=""
        local calc=""

        if [ "A$mask" != "A" ] && [ "A$ip" != "A" ]; then
            for i in {1..4}; do
                octMask=$(echo $mask | cut -d '.' -f $i)
                octIP=$(echo $ip | cut -d '.' -f $i)

                calc=$(($octMask & $octIP))
                res=$([ $i -eq 1 ] && echo $calc || echo "$res.$calc")
            done
        fi

        [ "$res" = "$net" ] && echo ok || echo ERROR
    fi
}

function downloadProjectList() {
    curl -s "$projectListName" -o $TMPFILE
    
    while read line; do
        projectList="${projectList}${line}!"
    done < $TMPFILE
}

function installDep() {
    echo_debug "Searching for dependance ..."
    for p in $packages; do
        res=$(command -v $p | wc -l)
        if [ $res -eq 1 ]; then
            echo_debug "Package $p found"
        else
            echo "Installing $p ..."
            if [ "A$VNC_PW" != "A" ]; then
                echo $VNC_PW | sudo -S apt-get -qq install $p >/dev/null 2>&1
            else
                sudo apt-get install $p
            fi
        fi
    done
}

function inputText() {
    if [ $exam -eq 1 ]; then
        while [ "A$firstName" = "A" ]; do
            read -p $"Enter your first name : " firstName
        done
        while [ "A$name" = "A" ]; do
            read -p $"Enter your name : " name
        done
    fi
    while [ "A$projectName" = "A" ]; do
        read -p $"Enter exercise name : " projectName

        projectFile="$(echo $projectName | cut -d '/' -f 2).mar"
        # projectFile="${projectName}.mar"
    done
    file="$projectName/$projectFile $projectName/$requestName $file"
}

function inputGraph() {
    if [ $exam -eq 1 ]; then
        local output=$(yad --form --title "input" \
        --field $"Enter exercise name":CBE $projectList \
        --field $"Enter your first name" \
        --field $"Enter your name" \
        --button=envoyer:0 \
        --button=gtk-cancel:1 \
        --on-top \
        --mouse)
    else
        local output=$(yad --form --title "input" \
        --field $"Enter exercise name":CBE $projectList\
        --button=envoyer:0 \
        --button=gtk-cancel:1 \
        --on-top \
        --mouse)
    fi
    
    if [ "A$output" != "A" ]; then
        if [ $exam -eq 1 ]; then
            if echo $output | grep -E ".+\|.+\|.+\|" &> /dev/null; then
                projectName=$(echo $output | cut -d '|' -f 1)
                firstName=$(echo $output | cut -d '|' -f 2)
                name=$(echo $output | cut -d '|' -f 3)
                # projectFile="${projectName}.mar"
            else
                echo_err $"All field must be completed"
                inputGraph
            fi
        else
            if echo $output | grep -E ".+\|" &> /dev/null; then
                projectName=$(echo $output | cut -d '|' -f 1)
                # projectFile="${projectName}.mar"
            else
                echo_err $"All field must be completed"
                inputGraph
            fi
        fi
        projectFile="$(echo $projectName | cut -d '/' -f 2).mar"
        file="$projectName/$projectFile $projectName/$requestName $file"
    else
        exitFunc 0
    fi
}

function verification() {
    local res=$(ps aux | grep marionnet | grep '\-daemon' | wc -l)
    if [ $res -eq 1 ]; then
        echo_debug $"Marionnet daemon is already running"
    else
        # sudo /etc/init.d/marionnet-daemon start
        if ! sudo service marionnet-daemon start; then
            echo_err $"Something wrong with marionnet daemon"
            exitFunc 1
        fi

        echo $"Marionnet daemon started"
    fi
    mkdir -p ~/.ssh
}

function launchMarionnet() {
    if [ -f $projectName/$projectFile ]; then
        res=$(ps aux | grep marionnet | grep $projectFile | wc -l)
        if [ $res -eq 0 ]; then 
            marionnet $projectName/$projectFile 2> /dev/null &
            echo $"Marionnet started"
        else
            echo_debug $"Marionnet already running"
        fi
    else
        echo_err $"Marionnet project $projectName/$projectFile does not exist"
        exitFunc 1
    fi
}

function getMarionnetFile() {
    if [ ! -d $projectName ]; then
        mkdir -p $projectName
    fi
    
    if curl -s $serverUrl/$projectName/ | grep '404 Not Found' &> /dev/null; then
        echo_err $"Id $projectName does not exist"
        rmdir $projectName
        exitFunc 1
    fi

    for f in $file; do
        curl -s $serverUrl/$f -o $TMPFILE
        f=$(echo $f | awk -F '/' '{print $NF}')

        if grep '404 Not Found' $TMPFILE &> /dev/null; then
            echo_err $"file $f does not exist"
            exitFunc 1
        fi
        
        if [ ! -f $projectName/$f ] || ! diff $projectName/$f $TMPFILE &> /dev/null; then 
            echo_debug $"Downloading $projectName/$f ..."
            cat $TMPFILE > $projectName/$f
        else
            echo_debug $"$projectName/$f already exist"
        fi
    done

    if [ -f $projectName/$idSsh ]; then
        res=$(ls -l $projectName/$idSsh | cut -d ' ' -f 1)
        if [ $res != "-rw-------" ]; then
            echo_debug $"Change chmod right to 600"
            chmod 600 $projectName/$idSsh
        fi
    fi
}

function parseRequest() {
    echo_debug "Parsing request ..."
    nbLine=$(grep label $projectName/$requestName 2> /dev/null | wc -l)
    local l=0

    if [ $nbLine -eq 0 ]; then
        echo_err $"Request file does not exist or is empty"
        exitFunc 1
    fi

    for i in $(seq 0 $((nbLine - 1))); do
        l=$((i+1))
        dataRequest[$l,1]=$(jq -r ".[$i].label" < $projectName/$requestName)
        dataRequest[$l,2]=$(jq -r ".[$i].command" < $projectName/$requestName)
    done

    [ $graph -eq 0 ] && echo $"$nbLine request found"
}

function parseCable() {
    # local pName=$(echo $projectFile | cut -d . -f 1)
    local pName=$(ls $TMPDIR/marionnet-*.dir/ 2> /dev/null | grep -Ev "^(hub|hublet|sparse-swap|switch)-")
    local patternD='DIRECT CABLE EDGES'
    local patternC='CROSSOVER/SERIAL CABLE EDGES'
    local char=""
    local m1=""
    local m2=""
    local i=0

    if [ "A$pName" = "A" ]; then
        echo_err $"Project not found"
        exitFunc 1
    fi
    
    echo_debug $"Parsing cable ..."

    while read line ; do
        if [ "$(echo $line)" == "$patternD" ]; then
            char='direct'
        elif [ "$(echo $line)" == "$patternC" ]; then
            char='cross'
        fi

        line=$(echo $line | grep ' -> ')
        if [ "A$line" != "A" ]; then
            line=$(echo $line | sed -e "s/^\([^(:| )]*\)[(:img:c)]* -> \([^(:| )]*\)[(:img:c)]* .*$/ \1 \2/")
            m1=$(echo $line | cut -d ' ' -f1)
            m2=$(echo $line | cut -d ' ' -f2)
            cable[$m1,$m2]=$char
            cable[$m2,$m1]=$char
        fi
    done < $TMPDIR/marionnet-*.dir/$pName/tmp/sketch.dot

    # nbCable=$i
}

function formatJson() {
    send="{\"data\":["
    for i in $(seq 1 $(( nbLine-1 ))); do
        send="$send\"${data[$i]}\","
    done
    send="$send\"${data[$nbLine]}\"], \"examMode\":$exam, \"projectName\":\"$projectName\""
    if [ $exam -eq 1 ]; then
        send="$send, \"firstName\":\"$firstName\", \"name\":\"$name\"}"
    else
        send="$send}"
    fi
}

function getDataText() {
    local show=""
    for i in $(seq 1 $nbLine); do
        show=$"Getting data $i/$nbLine : ${dataRequest[$i,1]} ..."
        [ $debug -eq 0 ] && echo -en "$show \r" || echo $show

        data[$i]=$(${dataRequest[$i,2]}) # execute la commande

        echo_debug "label : ${dataRequest[$i,1]}, command : ${dataRequest[$i,2]}, result : ${data[$i]}"
    done
    echo "======================Result======================"
}

function getDataGraph() {
    local tmp=""
    for i in $(seq 1 $nbLine); do
        echo $"# Getting data $i/$nbLine : ${dataRequest[$i,1]} ..."
        echo $((100 * $i / $nbLine))
        eval ${dataRequest[$i,2]} >> $TMPBUFF # execute la commande
    done | yad --progress --percentage=0 --auto-close --on-top --title $"Getting data" --mouse

    local i=1
    while read line ; do
        data[$i]=$line
        echo_debug "$i : ${dataRequest[$i,1]} : ${dataRequest[$i,2]} : $line" err
        i=$((i + 1))
    done < $TMPBUFF
    echo -n "" > $TMPBUFF
}

function parseResponse() {
    local resp=$(echo $response | jq .responses)
    local line=""

    if [ "A$resp" = "A" ]; then
        echo_err $"No response from server"
        exitFunc 1
    fi

    for i in $(seq 0 $((nbLine - 1))); do
        l=$((i + 1))
        line=$(echo $resp | jq ".[$i]")
        dr=$(echo $line | jq -r ".label")
        if [ "A$dr" = "Anull" ]; then break; fi
        dataResponse[$l,1]=$(echo $line | jq -r ".label") 
        dataResponse[$l,2]=$(echo $line | jq -r ".pts") 
        dataResponse[$l,3]=$(echo $line | jq -r ".comment") 
        dataResponse[$l,4]=$(echo $line | jq -r ".type") 
    done

    comment=$(echo $response | jq -r .grade.comment)
    type=$(echo $response | jq -r .grade.type)
}

# chooseColorWithType <type>
function chooseColorWithType() {
    if [ "A$1" != "A" ]; then
        local col=""
        
        if [ "$1" = "good" ]; then
            col=$([ $graph -eq 0 ] && echo "\e[32m" || echo "green")
        elif [ "$1" = "wrong" ] || [ "$1" = "mandatoryWrong" ]; then
            col=$([ $graph -eq 0 ] && echo "\e[31;1m" || echo "red")
        elif [ "$1" = "partial" ] || [ "$1" = "toleranceOut" ]; then
            col=$([ $graph -eq 0 ] && echo "\e[93;1m" || echo "orange")
        else
            col=$([ $graph -eq 0 ] && echo "\e[34m" || echo "blue")
        fi

        echo $col
    fi
}

function formatViewText() {
    view=""
    local color=""
    for i in $(seq 1 $nbLine); do
        color=$(chooseColorWithType ${dataResponse[$i,4]})
        if [ ${dataResponse[$i,4]} != "mandatoryGood" ] && [ ${dataResponse[$i,4]} != "toleranceOut" ]; then
            view="${view}${dataResponse[$i,1]} \t ${color}${dataResponse[$i,2]} \t ${dataResponse[$i,3]}\e[0m\n"
        fi
    done
    color=$(chooseColorWithType $type)
    view="${view}${color}${comment}\e[0m"
}

function formatViewGraph() {
    view=""
    local color=""
    for i in $(seq 1 $nbLine); do
        color=$(chooseColorWithType ${dataResponse[$i,4]})
        if [ "${dataResponse[$i,4]}" != "mandatoryGood" ] && [ "${dataResponse[$i,4]}" != "toleranceOut" ]; then
            view="${view}${dataResponse[$i,1]}; ${dataResponse[$i,2]}; ${dataResponse[$i,3]}; $color; white\n"
        fi
    done
    color=$(chooseColorWithType $type)
    view="$view;; $comment; $color; white"
}

function showViewGraph() {
    if [ $exam -eq 1 ]; then # en mode exam
        echo -e $view | awk -F ';' "$PARSER" |\
        yad --window-icon="gtk-execute" \
        --title="Vérif Marionnet exam"  \
        --button=gtk-close:1 \
        --geometry 600x350 --mouse \
        --list --no-click --no-selection \
        --text-align=center --text="Résultats" \
        --tail \
        --column CheckID:TXT \
        --column Note:TXT \
        --column Message:TXT \
        --column @back@ \
        --column @fore@
    else # en mode normal
        echo -e $view | awk -F ';' "$PARSER" |\
        yad --window-icon="gtk-execute" \
        --title="Vérif Marionnet"  \
        --button=revérifier:0 \
        --button=gtk-close:1 \
        --geometry 600x350 --mouse \
        --list --no-click --no-selection \
        --text-align=center --text="Résultats" \
        --tail \
        --column CheckID:TXT \
        --column Note:TXT \
        --column Message:TXT \
        --column @back@ \
        --column @fore@
    fi

    back=$?
}

function evaluation() {
    if [ $(ps aux |grep -c 'marionnet/kernels') = 1 ]; then
        echo_err $"No virtual machine or router is running !"
        exitFunc 1
    fi
    [ $graph -eq 0 ] && echo $"Evaluation in progress ..."

    parseRequest
    parseCable
    [ $graph -eq 1 ] && getDataGraph || getDataText
    formatJson

    response=$(curl -s -H "Content-Type: application/json" -X POST -d "$send" $serverPOST)

    parseResponse
    [ $graph -eq 1 ] && formatViewGraph || formatViewText
    [ $graph -eq 1 ] && showViewGraph || echo -e $view
}

function normalModeText() {
    launchMarionnet

    while [ "$choice" != "n" ]; do
        choice=""
        while [ "A$choice" = "A" ] || [ "$choice" != "y" ] && [ "$choice" != "n" ]; do
            read -p $"Do you want to check your marionnet project (y/n) : " choice
        done
        if [ "$choice" = "y" ]; then
            res=$(ps aux | grep marionnet | grep $projectFile | wc -l)
            if [ $res -eq 1 ]; then 
                evaluation
            else 
                echo_err $"Marionnet not launched"
                exitFunc 1
            fi
        else
            echo $"Good bye"
        fi
    done
}

function normalModeGraph() {
    launchMarionnet

    yad --image dialog-question \
    --title Evaluation \
    --button=gtk-yes:0 \
    --button=gtk-no:1 \
    --text $"Do you want to check your marionnet project ?" \
    --on-top \
    --mouse

    back=$?
    while [ $back -eq 0 ]; do
        res=$(ps aux | grep marionnet | grep $projectFile | wc -l)
        if [ $res -eq 1 ]; then 
            evaluation
        else 
            echo_err $"Marionnet not launched"
            exitFunc 1
        fi
    done
    echo $"Good bye"
}

function timerGraph() {
    local timer=0
    for sec in $(seq 0 $timing); do
        timer=$(date -d@$((timing - sec)) -u +%M:%S | awk -F : '{print $1, "min", $2, "s"}')
        echo "# $timer left ..."
        echo $((100 * sec / timing))
        sleep 1
    done | yad --progress --percentage=0 \
    --auto-close \
    --title Timer \
    --button "évaluer sans attendre:0" \
    --mouse
}

function timerText() {
    local timer=0
    for sec in $(seq 0 $timing); do
        timer=$(date -d@$((timing - sec)) -u +%M:%S | awk -F : '{print $1, "min", $2, "s"}')
        echo -en "$timer left ...\r"
        sleep 1
    done
}

function examModeText() {
    launchMarionnet

    echo $"Your are in exam mode, you have $timing seconds ..."
    timerText

    evaluation
}

function examModeGraph() {
    launchMarionnet
    timerGraph
    evaluation
}

installDep
downloadProjectList
verification
[ $graph -eq 1 ] && inputGraph || inputText
getMarionnetFile
if [ $exam -eq 1 ]; then
    [ $graph -eq 1 ] && examModeGraph || examModeText
else
    [ $graph -eq 1 ] && normalModeGraph || normalModeText
fi

rm -rf $TMPVERIF
perl -MFcntl -e 'fcntl STDIN, F_SETFL, fcntl(STDIN, F_GETFL, 0) & ~O_NONBLOCK'
