#!/bin/bash

if [[ $EUID -ne 0 ]]; then
   echo "You must be root to run this script" 
   exit 1
fi

packages="zenity wget ssh"
urlFile=""

name=""
firstName=""
idExam=""

function installDep() {
    echo "Searching for dependance ..."
    for p in $packages; do
        if [[ $(command -v $p | wc -l) -eq 1 ]]; then
            echo "Package $p found"
        else
            echo "Installing $p ..."
            apt install $p
        fi
    done
}

function input() {
    while [[ "A$name" = "A" ]]; do
        read -p "Enter your name : " name
    done
    while [[ "A$firstName" = "A" ]]; do
        read -p "Enter your first name : " firstName
    done
    while [[ "A$idExam" = "A" ]]; do
        read -p "Enter your exam id : " idExam
    done
    
    #echo "$name $firstName $idExam"
}

function verifDeamon() {
    if [[ $(ps aux | grep marionnet | grep daemon | wc -l) -eq 1 ]]; then
        echo "Marionnet daemon is already running"
    else
        /etc/init.d/marionnet-daemon start
        echo "Marionnet daemon stared"
    fi
}

function getMarionetFile() {
    echo "Downloading marionnet file"
    wget $urlFile
    filename="something"
    if [[ -d $filename ]]; then
        echo "Starting marionnet"
        marionnet $marionnetFile
    else
        echo "Marionnet file does not exist"
    fi
}

# installDep
# verifDeamon
# input
getMarionetFile

