#!/bin/bash

# ---------------- 
# marionnet_list
#
# list project and machines hostnames in the current active marionnet project 
#
# GNU Public License 3, Franck Butelle 2021
# ----------------

cde=$0

#-- Checks

if [ "A$TMPDIR" = "A" ]; then
	TMPDIR=/tmp
fi

resu=`ls -d $TMPDIR/marionnet-*.dir 2> /dev/null`
if [ "A$resu" = "A" ]; then
	echo "ERROR: No marionnet dir found in $TMPDIR, is it running ?"
	exit 1
fi
if [ `echo $resu | wc -l` -gt 1 ]; then
	echo "ERROR: more than one instance of marionnet detected, may be
	something wrong happened to some of them ?"
	echo "Please correct this first !"
	exit 1
fi

projectDIR=$(ls -d $TMPDIR/marionnet-*.dir)

echo "Marionnet project dir : "  $projectDIR

cd $projectDIR

projectName=$(ls |egrep -v '^(hub|hublet|switch|sparse-swap)-')

echo "Marionnet project name : " $projectName

for i in $(ls $projectName/hostfs); do
	echo $i : $(cat $projectName/hostfs/$i/GUESTNAME)
done

