#!/bin/bash

# ---------------- 
# marionnet_getVar host variable_name
#
# the host is the name of a running Virtual Machine of Marionnet
# GNU Public License 3, Franck Butelle 2021
# ----------------

cde=$0

#-- Checks
if [ "A$2" = "A" ]; then
	echo "Usage: $0  host var"
	echo "where host is the name of a virtual machine in marionnet"
	exit 1
fi

if [ "A$TMPDIR" = "A" ]; then
	TMPDIR=/tmp
fi

resu=`ls -d $TMPDIR/marionnet-*.dir 2> /dev/null`
if [ "A$resu" = "A" ]; then
	echo "ERROR: No marionnet dir found in $TMPDIR, is it running ?"
	exit 1
fi
if [ `echo $resu | wc -l` -gt 1 ]; then
	echo "ERROR: more than one instance of marionnet detected, may be
	something wrong happened to some of them ?"
	echo "Please correct this first !"
	exit 1
fi

Host="$1"
Var="$2"

resu=`ps aw |grep marionnet|grep "hostname=$Host "|head -1|sed -e 's/^.* '$Var'=\([^ ]*\) .*$/\1/'`'/'
if [ "$resu" = "/" ] ; then
	echo "ERROR : machine $Host not found in current marionnet project"
	exit 1
fi
echo $resu
